### ISSUE TITLE
It seems to be looking for Chrome

### ISSUE THREAD

**Issue by kevmimcc** [mipmip/docker-watir-xvfb#1]
This is what I got on a brand new install today:

/var/lib/gems/2.1.0/gems/selenium-webdriver-3.6.0/lib/selenium/webdriver/common/service.rb:59:in `binary_path':  Unable to find chromedriver. Please download the server from http://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH. More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. (Selenium::WebDriver::Error::WebDriverError)

**Comment by kevmimcc** [comment]
Probably need to specify an older version of watir to get code working as is.  After specifying to use Firefox, I now get this:

/var/lib/gems/2.1.0/gems/selenium-webdriver-3.6.0/lib/selenium/webdriver/common/service.rb:59:in `binary_path':  Unable to find Mozilla geckodriver. Please download the server from https://github.com/mozilla/geckodriver/releases and place it somewhere on your PATH. More info at https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver. (Selenium::WebDriver::Error::WebDriverError)

**Comment by kevmimcc** [comment]
Found the winning combination after many attempts of different versions of different things:


RUN gem install selenium-webdriver -v 2.53.4
RUN gem install watir-webdriver -v 0.9.1

I will make a pull request with this fix...
